services:
  rabbitmq:
    image: rabbitmq:4-management
    platform: linux/amd64
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:8
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec --save 900 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  celery-worker:
    build: .
    platform: linux/amd64
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbit@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: uv run celery -A app.celery worker -l INFO
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    platform: linux/amd64
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbit@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - celerybeat_data:/code/celery-beat
    command: uv run celery -A app.celery beat -s celery-beat/schedule -l INFO
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-flower:
    build: .
    platform: linux/amd64
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbit@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - celeryflower_data:/code/flower
    command: uv run celery -A app.celery flower --conf="./app/celery/flowerconfig.py"
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  rabbitmq_data:
  redis_data:
  celerybeat_data:
  celeryflower_data:
