services:
  rabbitmq:
    image: rabbitmq:4
    platform: linux/amd64
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery-worker:
    build: .
    platform: linux/amd64
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbit@rabbitmq:5672/
    command: uv run celery -A app worker -l INFO

volumes:
  rabbitmq_data:
